### ISSUE TITLE
อยากให้เพิ่มสถานะ ว่าโหลดแล้วหน้า view 

### ISSUE THREAD

**Issue by killmebabyx** [kon3ko/cover-next#1]
อยากให้เพิ่มสถานะ ว่าโหลดแล้วหน้า view  ให้หน่อยครับ
เหมือนผมเคยตามมาเวอร์ชั่นก่อนหน้าจะมีเลยชอบฟังชั่นนี้ครับ
ขอบคุณครับ

**Comment by kon3ko** [comment]
@killmebabyx  มีแล้วครับ ลองดูที่ตั้งค่ามุมล่างขวาจอนะครับ
