### ISSUE TITLE
Cover Next: เชื่อมต่อกับ Server Cache ล้มเหลว! 24/4/67

### ISSUE THREAD

**Issue by Nutty789** [kon3ko/cover-next#10]

**Comment by Nutty789** [comment]
เป็นๆหายๆครับ

**Comment by kon3ko** [comment]
เป็นบ่อยมากไหมครับ ช่วยแคปภาพมาดูหน่อยครับ

**Comment by Nutty789** [comment]
ผมหมายถึง รอบที่แล้วก็หายไปครั้งนึง ตอนผมทั้งโพส แล้วก็หายแล้ว เมื่อหลายวันก่อนก็หายไปอีก มันขึ้นเตือนตามที่พิมพ์อะครับ แต่ตอนนี้หายแล้ว

**Comment by kon3ko** [comment]
ครับเดี๋ยวถ้าเจออีกบอกทีนะครับ เดี๋ยวจะลองตรวจสอบแบบละเอียด ไม่แน่ใจเพราะเซิร์ฟล่มชั่วคราวแล้วมัน รีเซ็ตใหม่เองรึป่าวเลยหายเอง

**Comment by Nutty789** [comment]
เป็นอีกแล้วครับ Cover Next: เชื่อมต่อกับ Server Cache ล้มเหลว

**Comment by kon3ko** [comment]
เดี๋ยวเพิ่ม ระบบ connect ซ้ำอีกครั้งครับ เดาว่ามีการเชื่อมต่อพร้อมกันเยอะเกินไปครับ
