### ISSUE TITLE
รูปไม่แสดง

### ISSUE THREAD

**Issue by KHeight** [kon3ko/cover-next#11]
รูปที่เป็นของเว็บ https://uppic.cloud/ ไม่แสดงครับผม พอจะเพิ่มไปได้ไหมครับ

**Comment by kon3ko** [comment]
ขอลิงก์รูปภาพหน่อยครับ

**Comment by KHeight** [comment]
https://uppic.cloud/ib/WQRTNzbryz.jpg

**Comment by kon3ko** [comment]
เหมือนผมจะเข้าทั้งลิงก์เว็บ และลิงก์รูปไม่ได้เลยครับ
