### ISSUE TITLE
รูปไม่ขึ้น

### ISSUE THREAD

**Issue by DAF4Q** [kon3ko/cover-next#12]
รูปด้านข้างไม่ขึ้นครับ ต้องเอาเมาส์ไปชี้ตรงชื่อรูปถึงจะขึ้นครับ
![Screenshot 2024-04-27 145930](https://github.com/kon3ko/cover-next/assets/148269298/76d42f14-d9fb-47c0-a7c0-f93bb05fdea1)

**Comment by kon3ko** [comment]
เผลอไปปิดในตั้งค่าไว้ไหมครับ 
รูปฟันเฟือง อยู่มุมล่างขวาจอครับ

**Comment by DAF4Q** [comment]
ตอนนี้ภาพขึ้นปกติแล้วครับ
