### ISSUE TITLE
ปุ่มหาย

### ISSUE THREAD

**Issue by strikerzap** [kon3ko/cover-next#15]
เวลาปิดไม่ให้โชวปก แล้วปุ่มดาวโหลดไม่ขึ้นครับ ปกติไหม
![2024-05-10_225801](https://github.com/kon3ko/cover-next/assets/50877374/e24e003e-1c44-49f0-a997-0636355f409c)
![Uploading 2024-05-10_225801.jpg…]()

**Comment by kon3ko** [comment]
แก้ไขแล้วครับ V. 2.16
