### ISSUE TITLE
เว็บขึ้นแบบนี้ครับ โหลดรูปช้า

### ISSUE THREAD

**Issue by Naragonband** [kon3ko/cover-next#17]
Cover Next: เชื่อมต่อกับ Server Cache ล้มเหลว! [แจ้งปัญหาที่นี่](https://github.com/kon3ko/cover-next/issues)

![image](https://github.com/user-attachments/assets/7042d067-52d4-41f6-8d5f-d600df1e6608)

**Comment by b5270347** [comment]
เป็นเหมือนกันครับ

**Comment by kon3ko** [comment]
เดี๋ยวอัปเดตคืนนี้ครับ จะยกเลิก Server Cache ครับ

**Comment by Naragonband** [comment]
รอครับ ตอนนี้ยังไม่หาย

**Comment by rekio22** [comment]
พักหลังใช้แล้วภาพไม่โชว์เป็นเพราะอะไรครับ เป็นแบบนี้
![eee](https://github.com/user-attachments/assets/f1a630ef-cb6a-47a3-845d-7c68eb4f2fcb)

**Comment by b5270347** [comment]
เอาจริงมันโชว์อยู่นะครับ แต่ต้องเปิดแท็ปทิ้งไว้ซักพักนึงเลย
มันจะมีแจ้งเตือนด้านล่างว่า cache error
แต่ก็ยังโหลดภาพหน้าปกขึ้นโชว์อยู่ครับ

ในวันที่ ส. 10 ส.ค. 2024 เวลา 13:41 rekio22 ***@***.***>
เขียนว่า:

**Comment by linkinkue** [comment]
ลบลงใหม่ ตอนนี้นิ่งเลยครับ เหมือนปลั๊กอินไม่ทำงาน ไม่แจ้ง error อะไรอีกเลย

**Comment by linkinkue** [comment]
> เดี๋ยวอัปเดตคืนนี้ครับ จะยกเลิก Server Cache ครับ

ก่อนหน้านี้ใช้ได้แต่ช้าหน่อย ต้องรอสักพัก เพิ่งทราบว่ามีปัญหา ผมไม่รู้ก็เลยลบลงใหม่ ตอนนี้ใช้ไม่ได้เลยครับ ไม่น่ารีบลบเลย รอนะครับ เป็นกำลังใจให้ทีมงานทุกท่าน

**Comment by kon3ko** [comment]
แก้ไขแล้วครับ https://github.com/kon3ko/cover-next/commit/8a81087f1c03046672b0d19360c24b9f8c5c20f1
