### ISSUE TITLE
Header ช่องรูปภาพหาย

### ISSUE THREAD

**Issue by amajio** [kon3ko/cover-next#18]
เป็น bug เล็กๆ ไม่กระทบอะไรเยอะ > Header ช่องรูปภาพไม่มี ทำให้ชื่อ Column ไม่ตรงช่อง
![image](https://github.com/user-attachments/assets/28fea328-d8ab-4af1-9182-00a0d36c4cd8)

**Comment by kon3ko** [comment]
ขอลิงก์ของหน้านี้หน่อยครับ

**Comment by amajio** [comment]
> ขอลิงก์ของหน้านี้หน่อยครับ

ลองดูแล้วเป็นทุกหน้านะครับ เลือกแทบทุกหมวดแล้วเป็นหมดเลยครับ

**Comment by kon3ko** [comment]
รับเรื่องครับ มีปัญหากับคนที่ไม่ได้เป็น VIP ของเว็บครับ
เดี๋ยวว่างแล้วอัปเดตแก้ไขให้นะครับ

**Comment by kon3ko** [comment]
fix in 2.21
