### ISSUE TITLE
ช่วย Update Selector src/modules/serial.js ให้หน่อยครับ

### ISSUE THREAD

**Issue by nutpaker** [kon3ko/cover-next#19]
##ช่วย Update Selector

src/modules/serial.js  line 19 ให้ทีครับ

ขอบคุณครับ

**Comment by kon3ko** [comment]
ไม่เข้าใจครับ ติดปัญหาด้านไหนครับ?

**Comment by nutpaker** [comment]
ผมติดปัญหาเรื่อง highlight ข้อความในรายการที่ ดาวโหลดไปแล้วครับ 
ผมไม่อยากเข้าไปแก้ ที่ function donateVersion 
แต่ผมอยากให้ทำให้มันถูกต้องคือต้องแก้ src/modules/serial.js และกำหนด Selector Jquery ที่เข้ารหัสไว้ ใหม่ ครับ
เพราะอันเก่ามันใช้ไม่ได้แล้ว 
ขอบคุณครับ
