### ISSUE TITLE
รูปไม่แสดงครับ ไม่สามารถใช้งานได้

### ISSUE THREAD

**Issue by KristyKQ** [kon3ko/cover-next#21]

**Comment by kon3ko** [comment]
ขอรูปหน่อยครับ ผมเข้าแล้วปกติ

**Comment by KristyKQ** [comment]
![Screenshot_20241122_235259_Kiwi Browser](https://github.com/user-attachments/assets/a8ed7343-3745-4039-8f63-f15f42899b5a)
![Screenshot_20241122_235205_Kiwi Browser](https://github.com/user-attachments/assets/fe09857f-0b22-47f3-9e33-47666db94f29)
![Screenshot_20241122_235150_Kiwi Browser](https://github.com/user-attachments/assets/b5347260-cd82-463d-be6c-4ad41a602008)

**Comment by kon3ko** [comment]
ไม่เห็นปุ่ม setting มุมขวาล่าง น่าจะติดตั้งไม่ถูกรึป่าวครับ?
