### ISSUE TITLE
ภาพปก ชี้แล้วไม่ขึ้นในหมวดต่างๆ

### ISSUE THREAD

**Issue by FiRSTTX** [kon3ko/cover-next#5]
ภาพปก ชี้แล้วไม่ขึ้นในหมวดต่างๆ แต่ หมวด18+ ขึ้นปกตินะครับ

![Screenshot 2024-03-01 233535](https://github.com/kon3ko/cover-next/assets/144312867/6e1e9a3f-00a5-4b74-9aec-185c6d6a4d20)

**Comment by kon3ko** [comment]
รูปภาพหน้าปกจะใช้งานไม่ได้ สำหรับสมาชิกที่ไม่ได้เป็น Premium ของ Bearbit อีกต่อไปจนกว่าทางเว็บจะนำไอค่อนรูปกล้องกลับมาในหน้ารายการเลือกไฟล์ครับ

ส่วนสมาชิกที่เป็น Premium จะมีไอค่อนครับ และระบบทำงานปกติครับ

![image](https://github.com/kon3ko/cover-next/assets/50349884/83dd2ac8-9806-4462-a4da-c09da6eef044)
