### ISSUE TITLE
ภาพยังไม่ขึ้นครับ กด view เเล้วข้อมูลภาพไม่ตรงครับ

### ISSUE THREAD

**Issue by dirrenjersa** [kon3ko/cover-next#6]
![untitled](https://github.com/kon3ko/cover-next/assets/108389801/0f1eaced-72d9-48cd-9b98-0f30f3341a09)

![untitled1](https://github.com/kon3ko/cover-next/assets/108389801/87749176-d4c7-481e-b866-0d1118dd3091)

**Comment by kon3ko** [comment]
#5 Duplicate
