### ISSUE TITLE
พี่ครับ อัพเดทมาใหม่ต้องกด thank เองครับ

### ISSUE THREAD

**Issue by 0xiSpys** [kon3ko/cover-next#8]
![Untitled](https://github.com/kon3ko/cover-next/assets/113327146/e460ac8b-abc2-4d34-b207-e33ce6ced274)

**Comment by kon3ko** [comment]
เนื่องจากเว็บแสดงปุ่มดาวน์โหลดหน้ารายการสำหรับ สมาชิกที่ไม่ใช่ premium ครับ ปกติมีแค่ premium 

ไม่รู้บัครึป่าวครับ เดี๋ยวผมอัปเดตแก้ให้ครับ

**Comment by kon3ko** [comment]
เว็บเอาปุ่มออกแล้ว
